name: Hourly Integration (kovan)
on:
  schedule:
    - cron: '0 * * * *'  # every hour on the hour     

jobs:
  push_to_branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_SLACK_WEBHOOK }}
    steps:
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          repository: provideplatform/ident
          path: 'ident'
          ref: dev
      - name: Checkout nchain
        uses: actions/checkout@v2
        with:
          ref: dev        
          path: 'nchain'                    
      - run: docker build -t nchain/local --no-cache .
        working-directory: nchain
      - run: docker-compose -f ./ops/docker-compose.yml up -d
        working-directory: nchain
      - run: TAGS=kovan ./ops/run_local_tests_short.sh
        working-directory: nchain      
      - run: docker-compose -f ./ops/docker-compose.yml logs
        working-directory: nchain
      - name: log on failure
        if: failure()
        run: docker-compose -f ./ops/docker-compose.yml logs
        working-directory: nchain
      - name: Send Slack Notification
        if: failure()  
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}