name: NChain
on:
  push:
    branches:
      - feature/github-actions-production

jobs:
#   push-to-registry:
#     name: Push Docker Image
#     runs-on: ubuntu-latest
#     steps:
#       - name: Clone Repo
#         id: checkout
#         uses: actions/checkout@v2
#       - name: Push Docker Image 
#         uses: docker/build-push-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_PAT }}
#           repository: provide/nchain
#           tags: "latest"
  push-to-production:
    name: Update Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ci-process.sh
        shell: bash
        env:
          AWS_ACCOUNT_ID: ${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.PRODUCTION_AWS_DEFAULT_REGION }}
          AWS_DEFAULT_OUTPUT: json
          ECR_REPOSITORY_NAME: hardcode
          ECS_TASK_DEFINITION_FAMILY: hardcode
          ECS_CLUSTER: production
          ECS_SERVICE_NAME: hardcode
          RUN_INTEGRATION_SUITE: false
        run: |
          chmod +x "${GITHUB_WORKSPACE}/ops/ci-process.sh"
          "${GITHUB_WORKSPACE}/ops/ci-process.sh"
